### PR TITLE
Google maps implementation

### PR DESCRIPTION
**Pull request by CSumm**
-MiniMap created of different sizes using styled components in app/component/MiniMap.jsx
-Mnimap storybook file created in app/component/MiniMap.stories.js

### CODE REVIEW

**Comment by mat10tng** [comment]
Do we have to eject create-react-app? What is the reason for this?

**Comment by CSumm** [comment]
I'll fetch the updates and update this PR

**Comment by CSumm** [comment]
Should I close the PR and do another pull request with the updated fork for the feature?

**Comment by CSumm** [comment]
Closing and putting in the new PR to reflect updated fork

**Comment by mat10tng** [comment]
Hi, I think that is for the best, otherwise, we might have a lot of changes in history.

**Pull request closed without merging**
